name: e_bandobas
version: 1.0.0+1
publish_to: 'none'
description: A new Flutter project.
environment:
  flutter: ">=2.0.0 <3.0.0"
  sdk: '>=2.18.0-314.0.dev <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  responsive_grid_list: ^1.3.0
  http: ^0.13.5
  syncfusion_flutter_datagrid: ^20.3.56
  intl: ^0.17.0
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  localization: ^2.1.0
  provider: ^6.0.5
  html: ^0.15.1
  dropdown_search: ^5.0.1
  dio: ^5.0.3
  flutter_staggered_grid_view: ^0.6.2
  path_provider: ^2.0.13
  url_launcher: ^6.1.10
  open_file_plus: ^3.4.0
  animated_text_kit: ^4.2.2
  file_picker: ^5.2.5
  window_manager: ^0.2.7


dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/